import { useRef, useState } from "react"
import { Link } from "react-router-dom"
import quiezIcon from "@/assets/global/quiz.svg"
import data from "../../data/topics.json"

import DifImageOne from "@/assets/topics/renewable/definition/image1.png"
import DifImageTwo from "@/assets/topics/renewable/definition/image2.png"
import DifImageThree from "@/assets/topics/renewable/definition/image3.png"
import EffImageOne from "@/assets/topics/renewable/effects/image1.png"
import EffImageTwo from "@/assets/topics/renewable/effects/image2.png"
import EffImageThree from "@/assets/topics/renewable/effects/image3.png"
import SolImageOne from "@/assets/topics/renewable/solution/image1.png"
import SolImageTwo from "@/assets/topics/renewable/solution/image2.png"
import SolImageThree from "@/assets/topics/renewable/solution/image3.png"

import useSmoothScroll from "@/hooks/useSmoothScroll"

import "./index.css"

const RenewableEnergy = () => {
  const topic = data.topics.find(t => t.id === "renewable-energy")!

  const sections = ["Definition", "Effects", "Solutions"] as const
  const [section, setSection] = useState<"Definition" | "Effects" | "Solutions">("Definition")

  const targetRef = useRef<HTMLElement>(null)
  useSmoothScroll(400, targetRef)

  return (
    <section className="px-10 lg:px-20">
      <header className="flex flex-wrap items-end justify-between">
        <h2 className="text-nowrap text-lg font-bold sm:text-2xl md:text-3xl">
          <span className="text-[#0B539B]">Learn about </span>
          <span className="text-[#86A41E]">{topic.title}</span>
        </h2>
        <Link
          to={`quiz`}
          className="ml-auto flex items-center justify-center gap-2 text-nowrap rounded-[20px] font-medium text-[#0B539B] max-sm:text-sm md:bg-[#E4FF87] md:px-5 md:py-3 md:text-base md:font-bold"
        >
          <img src={quiezIcon} alt="" className="size-[20px] md:size-[27px]" />
          Go to Quiz
        </Link>
      </header>
      <nav ref={targetRef} className="ml-auto mr-auto mt-10 flex w-full max-lg:justify-between lg:mt-5 lg:justify-center lg:gap-[60px]">
        {sections.map(item => (
          <button
            key={item}
            onClick={() => setSection(item)}
            className={`text-nowrap rounded-[20px] border-[#0B539B] font-medium duration-300 sm:text-xl md:text-2xl lg:h-[65px] lg:w-[212px] lg:border-[1px] ${section === item ? "text-[#0B539B] lg:bg-[#0B539B] lg:text-white" : ""}`}
          >
            {`${item}`}
          </button>
        ))}
      </nav>

      <iframe
        src={`https://www.youtube.com/embed/${topic.video}`}
        title="YouTube video player"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
        className="mx-auto mt-20 h-[200px] w-[350px] rounded-[1rem] sm:h-[280px] sm:w-[500px] md:h-[340px] md:w-[600px] lg:h-[450px] lg:w-[800px]"
      ></iframe>

      <section className="mt-20 pb-20">
        {section === "Definition" && (
          <>
            <figure className="flex items-center justify-between gap-10 max-lg:flex-col lg:justify-evenly">
              <img src={DifImageOne} alt="" className="max-sm:w-[300px]" />
              <figcaption className="max-w-[488px] text-center">
                <h2 className="text-2xl font-bold text-[#0B539B] sm:text-3xl">What is Renewable Energy ?</h2>
                <p className="font-bold text-[hsla(0,0%,0%,0.62)] sm:text-[20px]">
                  Renewable energy comes from natural sources that are constantly replenished, such as sunlight, wind, rain, tides, waves, and geothermal heat. Unlike fossil fuels, renewable energy
                  sources do not deplete over time and have a much lower environmental impact.
                </p>
              </figcaption>
            </figure>
            <figure className="my-20 flex items-center justify-between gap-10 max-lg:flex-col lg:my-32 lg:justify-evenly">
              <figcaption className="order-2 max-w-[488px] text-start md:order-1">
                <h2 className="text-2xl font-bold text-[#0B539B] sm:text-3xl">Types of Renewable Energy</h2>
                <h3 className="text-lg font-bold sm:text-[20px]">1. Solar Energy</h3>
                <p className="dots *:block sm:text-[20px]">
                  <span>Solar energy is harnessed from the sun using photovoltaic cells or solar thermal systems.</span>
                  <span>Applications: Solar panels on rooftops, solar farms, solar water heaters.</span>
                  <span>Innovations: Floating solar panels, perovskite solar cells1.</span>
                </p>
                <h3 className="text-lg font-bold sm:text-[20px]">2. Wind Energy</h3>
                <p className="dots *:block sm:text-[20px]">
                  <span>Description: Wind energy is generated by converting wind currents into electricity using wind turbines.</span>
                  <span>Applications: Onshore and offshore wind farms.</span>
                  <span>Innovations: Small-scale wind turbines for urban areas, vertical-axis wind turbines2.</span>
                </p>
              </figcaption>
              <img src={DifImageTwo} alt="" className="max-sm:w-[300px] md:order-1" />
            </figure>
            <figure className="flex items-center justify-between max-lg:flex-col lg:justify-evenly">
              <img src={DifImageThree} alt="" className="max-sm:w-[300px]" />
              <figcaption className="max-w-[488px] text-start">
                <h3 className="text-lg font-bold sm:text-[20px]">3. Hydropower</h3>
                <p className="dots *:block sm:text-[20px]">
                  <span>Solar energy is harnessed from the sun using photovoltaic cells or solar thermal systems.</span>
                  <span>Applications: Solar panels on rooftops, solar farms, solar water heaters.</span>
                  <span>Innovations: Floating solar panels, perovskite solar cells1.</span>
                </p>
                <h3 className="text-lg font-bold sm:text-[20px]">4. Biomass Energy</h3>
                <p className="dots *:block sm:text-[20px]">
                  <span>Description: Wind energy is generated by converting wind currents into electricity using wind turbines.</span>
                  <span>Applications: Onshore and offshore wind farms.</span>
                  <span>Innovations: Small-scale wind turbines for urban areas, vertical-axis wind turbines2.</span>
                </p>
              </figcaption>
            </figure>
          </>
        )}
        {section === "Effects" && (
          <>
            <figure className="flex items-center justify-between gap-10 max-lg:flex-col lg:justify-evenly">
              <img src={EffImageOne} alt="" className="max-sm:w-[300px]" />
              <figcaption className="max-w-[488px] text-center">
                <h2 className="mb-5 text-2xl font-bold text-[#0B539B] sm:text-3xl">Benefits of Renewable Energy ?</h2>
                <p className="font-bold text-[hsla(0,0%,0%,0.62)] sm:text-[20px]">Environmental Impact, Sustainability, Economic Growth, Energy Security.</p>
              </figcaption>
            </figure>
            <figure className="my-20 flex items-center justify-between gap-10 max-lg:flex-col lg:my-32 lg:justify-evenly">
              <figcaption className="order-2 max-w-[488px] text-start md:order-1">
                <h2 className="mb-5 text-2xl font-bold text-[#0B539B] sm:text-3xl">Impacts of Renewable Energy</h2>
                <h3 className="text-lg font-bold sm:text-[20px]">1. Environmental Impact</h3>
                <p className="text-[hsla(0,0%,0%,0.62)] sm:text-[20px]">
                  <span>Reduces greenhouse gas emissions and air pollution.</span>
                </p>
                <h3 className="text-lg font-bold sm:text-[20px]">2. Sustainability</h3>
                <p className="text-[hsla(0,0%,0%,0.62)] sm:text-[20px]">
                  <span> Provides a sustainable energy source that does not deplete over time.</span>
                </p>
              </figcaption>
              <img src={EffImageTwo} alt="" className="max-sm:w-[300px] md:order-1" />
            </figure>
            <figure className="flex items-center justify-between max-lg:flex-col lg:justify-evenly">
              <img src={EffImageThree} alt="" className="max-sm:w-[300px]" />
              <figcaption className="max-w-[488px] text-start">
                <h3 className="text-lg font-bold sm:text-[20px]">3. Economic Growth</h3>
                <p className="text-[hsla(0,0%,0%,0.62)] sm:text-[20px]">
                  <span>Creates jobs and stimulates economic growth in the renewable energy sector.</span>
                </p>
                <h3 className="text-lg font-bold sm:text-[20px]">4. Energy Security </h3>
                <p className="text-[hsla(0,0%,0%,0.62)] sm:text-[20px]">
                  <span>Reduces dependence on imported fossil fuels and enhances energy security.</span>
                </p>
              </figcaption>
            </figure>
          </>
        )}
        {section === "Solutions" && (
          <>
            <figure className="flex items-center justify-between gap-10 max-lg:flex-col lg:justify-evenly">
              <img src={SolImageOne} alt="" className="max-sm:w-[300px]" />
              <figcaption className="max-w-[488px] text-center">
                <h2 className="text-2xl font-bold text-[#0B539B] sm:text-3xl">Solution of Energy Challenges?</h2>
                <p className="font-bold text-[hsla(0,0%,0%,0.62)] sm:text-[20px]">There are many kinds of solutions such as : Transition to Renewable, Energy Sources, Nuclear Power</p>
              </figcaption>
            </figure>
            <figure className="my-20 flex items-center justify-between gap-10 max-lg:flex-col lg:my-32 lg:justify-evenly">
              <figcaption className="order-2 max-w-[488px] text-start md:order-1">
                {/* <h2 className="text-2xl font-bold text-[#0B539B] sm:text-3xl">Types of Renewable Energy</h2> */}
                <h3 className="text-lg font-bold sm:text-[20px]">1. Intermittency</h3>
                <p className="text-[hsla(0,0%,0%,0.62)] sm:text-[20px]">
                  Renewable energy sources like solar and wind are intermittent. Solutions include energy storage systems (e.g., batteries) and grid integration.
                </p>
                <h3 className="text-lg font-bold sm:text-[20px]">2. Initial Costs</h3>
                <p className="text-[hsla(0,0%,0%,0.62)] sm:text-[20px]">
                  High initial costs for renewable energy installations. Solutions include government incentives, subsidies, and technological advancements that reduce costs over time.
                </p>
              </figcaption>
              <img src={SolImageTwo} alt="" className="max-sm:w-[300px] md:order-1" />
            </figure>
            <figure className="flex items-center justify-between max-lg:flex-col lg:justify-evenly">
              <img src={SolImageThree} alt="" className="max-sm:w-[300px]" />
              <figcaption className="max-w-[488px] text-start">
                <h3 className="mt-5 text-lg font-bold sm:text-[20px]">3.Infrastructure</h3>
                <p className="text-[hsla(0,0%,0%,0.62)] sm:text-[20px]">
                  Need for infrastructure development to support renewable energy. Solutions include smart grids and decentralized energy systems.
                </p>
                <h3 className="text-lg font-bold sm:text-[20px]">4. Biomass Energy</h3>
                <p className="dots *:block sm:text-[20px]">
                  <span>Description: Biomass energy is produced from organic materials such as plant and animal waste.</span>
                  <span>Applications: Biofuels, biogas, biomass power plants.</span>
                  <span>Innovations: Advanced biofuels, algae-based bioenergy3</span>
                </p>
              </figcaption>
            </figure>
          </>
        )}
      </section>
    </section>
  )
}

export default RenewableEnergy
